name: WiPP
channels:
  - bioconda
  - conda-forge
  - cran
  - defaults
dependencies:
  - snakemake-minimal=5.4.3
  - appdirs=1.4.3
  - asn1crypto=0.24.0
  - attrs=18.2.0
  - bzip2=1.0.6
  - ca-certificates=2018.11.29
  - certifi=2018.11.29
  - cffi=1.11.5
  - chardet=3.0.4
  - configargparse=0.13.0
  - cryptography=2.3.1
  - docutils=0.14
  - gitdb2=2.0.5
  - gitpython=2.1.11
  - idna=2.8
  - jsonschema=3.0.0a3
  - libffi=3.2.1
  - libstdcxx-ng=7.2.0
  - ncurses=6.1
  - openssl=1.0.2p
  - pip=18.1
  - psutil=5.4.8
  - pycparser=2.19
  - pyopenssl=18.0.0
  - pyrsistent=0.14.7
  - pysocks=1.6.8
  - python=3.7.1
  - pyyaml=3.13
  - ratelimiter=1.2.0
  - readline=7.0
  - requests=2.21.0
  - setuptools=40.6.2
  - six=1.12.0
  - smmap2=2.0.5
  - sqlite=3.26.0
  - tk=8.6.9
  - urllib3=1.24.1
  - wheel=0.32.3
  - wrapt=1.10.11
  - xz=5.2.4
  - yaml=0.1.7
  - zlib=1.2.11
  - datrie=0.7.1
  - libgcc-ng=8.2.0
  - pip:
    - cftime==1.0.3.4
    - cycler==0.10.0
    - kiwisolver==1.0.1
    - matplotlib==3.0.2
    - netcdf4==1.4.2
    - numpy==1.15.4
    - pandas==0.23.4
    - pyopenms==2.4.0
    - pyparsing==2.3.0
    - python-dateutil==2.7.5
    - pytz==2018.7
    - scikit-learn==0.20.1
    - scipy==1.1.0
    - sklearn==0.0
    - pytools==2018.5.2
